---
title: "T cells: Ontogeny and Maintenance"
author: "Sanket Rane"
institute: "IICD & Dept of Patholgy and Cell Biology"
date: "`r Sys.Date()`"

output:
  xaringan::moon_reader:
    #chakra: libs/remark-latest.min.js
    css: [My-xaringan-themer.css, xaringan-custom.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      #slideNumberFormat: "%current%"
      
---
class: center, middle

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "100%", cache = FALSE)
library(tidyverse)
library(knitr)
```



```{r xaringan-themer, include=FALSE}
library(xaringanthemer)
 style_mono_accent(
  base_color = "#F97B64",
  header_font_google = google_font("Yanone Kaffeesatz"),
  text_font_google   = google_font("IBM Plex Sans", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  header_color = "#035AA6"
)

```




```{r child='intro.Rmd'}
```

---

```{r child='data_ontogeny.Rmd'}
```

---

```{r child='fits_ontogeny.Rmd'}
```

---


```{r child='timestamp.Rmd'}
```













